[package]
name = "peroxide-cryptsetup"
version = "0.1.0"
authors = ["Vladimir Lushnikov <vladimir@solidninja.is>"]
build = "build.rs"

[features]
default = ["yubikey", "yubikey_hybrid"]
yubikey = ["ykpers-rs"]
yubikey_hybrid = ["yubikey", "sodiumoxide"]

[build-dependencies]
syntex = "*"
serde_codegen = { version = "*", features = ["with-syntex"] }

[dependencies]
docopt = "*"
rustc-serialize = "*"
serde = "*"
serde_json = "*"
uuid = "*"
errno = "*"
sodiumoxide = { version = "*", optional = true }

# TODO - decide on what logger to use :)
log = "*"
env_logger = "*"
termios = "*"
libc = "*"

cryptsetup-rs = { version = "0.1.0", path = "lib/cryptsetup-rs" }
ykpers-rs = { version = "0.1.0", path = "lib/ykpers-rs", optional = true }

[dev-dependencies]
tempfile = "*"
tempdir = "*"
env_logger = "*"
expectest = "*"

[lib]
name = "peroxide_cryptsetup"
path = "src/lib/lib.rs"

[[bin]]
name = "peroxs"
test = false
doc = false

[[test]]
name = "tests"

[profile.dev]
codegen-units = 4

[profile.test]
codegen-units = 4
